version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default

  file:
    class: logging.FileHandler
    filename: app.log
    level: DEBUG
    formatter: default

root:
  level: DEBUG
  handlers: [console, file]